import SideSection from "@/Components/BodySection/SideSection";
import Footer from "@/Components/Footer/Footer";
import HeaderMenu from "@/components/HeaderMenu/Header";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Mental Press",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{
          backgroundImage: `url('/pattern.png')`,
          backgroundRepeat: "repeat",
        }}
      >
        <HeaderMenu />
        <main className="flex flex-col items-center justify-between w-full">
          <div className="w-full">
            <div className="w-full px-24 bg-transparent flex flex-col gap-y-6">
              <div className="flex justify-between mb-12 gap-6">
                <div className="w-[270px] order-1">
                  <SideSection />
                </div>
                <div className="order-2">{children}</div>
              </div>
            </div>
          </div>
        </main>
        <Footer />
      </body>
    </html>
  );
}
