export const allBlogs = [
  {
    image: "/blog1.jpg",
    header: "Ways to help your children develop self-esteem and confidence",
    tag: "CHILDREN THERAPY",
    motherTag: "Children",
    date: "February 23, 2015",
    author: "Jaka Smid",
    body: "Self-esteem and confidence are major traits in individuals that affect their success. While these are a lifelong process, the foundation of it needs to be established in early childhood. Building self-esteem will allow the child to deal with difficult situations that they will encounter during their lifetime. Since parents have the greatest influence on a child's belief, it is important for them to let their child know where they belong, how well they are doing and contribute towards developing confidence and self-esteem.",
  },
  {
    image: "/blog2.jpg",
    header: "Looking for help is sign of strength",
    tag: "TEENAGE",
    motherTag: "Youngsters",
    date: "February 23, 2015",
    author: "Jaka Smid",
    body: "Individual treatment is often termed as psychotherapy, and is meant to help people with their emotional issues, which can range in order of their severity or intensity. The main aim of this form of therapy is to change the quality of life by defining the path of life clearly, and bringing in more clarity. Whether it is the problem of repressed childhood that you are facing, or an emotional breakdown due to divorce, failure or loss of a loved one, a professional psychologist can help you revive your mental health through systematic counselling.",
  },
  {
    image: "/blog3.jpg",
    header: "Get the most out of your work day",
    tag: "THERAPY",
    motherTag: "Work",
    date: "February 23, 2015",
    author: "Jaka Smid",
    body: "There are many emotional issues that find a corner in our heart, and refuse to die down. With time, these issues can transform into a sort of emotional tumor that impacts negatively on our daily life, such as lack of concentration, enthusiasm, self respect, will to change, encouragement, and so on. These issues can spiral into our lives in various ways and gets channelled into other zones, which can create problems in the relationships, professional life, and health.",
  },
  {
    image: "/blog4.jpg",
    header: "Help your child find new friends",
    tag: "CHILDREN THERAPY",
    motherTag: "Friendship",
    date: "February 23, 2015",
    author: "Jaka Smid",
    body: "Anxiety is something that exists in everyone's life to a certain extent, and in a way it is medically known to be helpful as well. Because, anxiety helps us stay alert and be reactive to our circumstances, whether joyful or painful. However, when the anxiety reaches the stage where it overwhelms you mentally and physically, and affects your normal routine of life, you need the help of a clinical psychologist.",
  },
  {
    image: "/blog5.jpg",
    header: "It is never to late to go to therapy",
    tag: "INDIVIDUAL TREATMENT",
    motherTag: "Elderly",
    date: "February 23, 2015",
    author: "Jaka Smid",
    body: "We define the goals and objectives of the counselling sessions in a very transparent manner to help patients overcome their problems quickly and effectively, and get the new lease of life they came looking for. We work with the patient as per their schedule, to fix an appointment that is mutually agreeable. We help you embrace life, the way it is meant to be.",
  },
  {
    image: "/blog6.jpg",
    header: "Put yourself on the first place",
    tag: "INDIVIDUAL TREATMENT",
    motherTag: "Individual",
    date: "February 23, 2015",
    author: "Jaka Smid",
    body: "Individual treatment is often termed as psychotherapy, and is meant to help people with their emotional issues, which can range in order of their severity or intensity. The main aim of this form of therapy is to change the quality of life by defining the path of life clearly, and bringing in more clarity. Whether it is the problem of repressed childhood that you are facing, or an emotional breakdown due to divorce, failure or loss of a loved one, a professional psychologist can help you revive your mental health through systematic counselling.",
  },
  {
    image: "/blog7.jpg",
    header: "Anxiety treatment for better tomorrow",
    tag: "ANXIETY",
    motherTag: "Anxiety",
    date: "February 23, 2015",
    author: "Jaka Smid",
    body: "Anxiety is something that exists in everyone's life to a certain extent, and in a way it is medically known to be helpful as well. Because, anxiety helps us stay alert and be reactive to our circumstances, whether joyful or painful. However, when the anxiety reaches the stage where it overwhelms you mentally and physically, and affects your normal routine of life, you need the help of a clinical psychologist.",
  },
  {
    image: "/blog8.jpg",
    header: "Don't be embarrassed to go on couples therapy",
    tag: "COUPLES THERAPY",
    motherTag: "Couples",
    date: "February 23, 2015",
    author: "Jaka Smid",
    body: "We define the treatment path in couples therapy after patiently listening and carefully understanding the problems couple is facing. Our practical and scientific approach, while balancing and weighing the emotions at stake, helps us bring in the much needed transparency and attachment among the partners. It definitively helps in doing the right thing, and taking the right decision, not only for the relationship, but personally as well.",
  },
  {
    image: "/blog9.jpg",
    header: "10 tips for less stressful mornings",
    tag: "STRESS",
    motherTag: "stress",
    date: "February 23, 2015",
    author: "Jaka Smid",
    body: "Self-esteem and confidence are major traits in individuals that affect their success. While these are a lifelong process, the foundation of it needs to be established in early childhood. Building self-esteem will allow the child to deal with difficult situations that they will encounter during their lifetime. Since parents have the greatest influence on a child's belief, it is important for them to let their child know where they belong, how well they are doing and contribute towards developing confidence and self-esteem.",
  },
  {
    image: "/blog10.jpg",
    header: "Spend more time with your children and improve their confidence",
    tag: "CONFIDENCE",
    motherTag: "Confidence",
    date: "February 23, 2015",
    author: "Jaka Smid",
    body: "In today's competitive world, sleep is more of a luxury than a necessity. Sleep is important for the well being, both emotionally and physically for an individual. Insufficient sleep or no sleep has long lasting health and psychological disorders. If you have been experiencing insomnia, it may be due to a number of factors, including stress, anxiety or depression. In order to address your sleep problem, it is best to consult an experienced psychologist who can help you change your behaviour, manage feelings and emotions that may interfere with your sleep.",
  },
  {
    image: "/blog11.jpg",
    header: "How to improve your memory?",
    tag: "SELF-IMPROVEMENT",
    motherTag: "Memory",
    date: "February 23, 2015",
    author: "Jaka Smid",
    body: "It has been believed for centuries that as we grow older, our brain functions continue to deteriorate, which also impacts and weakens our memory. However, recent medical researches and experiments have proved that our brain has the ability to grow new neurons, even as we age, a process known scientifically as neuroplasticity. The mental health of a person depends vastly on how active the person is - physically and mentally. If you keep forgetting things too quickly, or have noticed a sharp decline in your mental health in terms of memory recently, it is time to make some really important changes in your lifestyle to help sharpen and improve your memory.",
  },
  {
    image: "/blog12.jpg",
    header: "How to get a good nights sleep?",
    tag: "SELF-IMPROVEMENT",
    motherTag: "Insomnia",
    date: "February 23, 2015",
    author: "Jaka Smid",
    body: "In today's competitive world, sleep is more of a luxury than a necessity. Sleep is important for the well being, both emotionally and physically for an individual. Insufficient sleep or no sleep has long lasting health and psychological disorders. If you have been experiencing insomnia, it may be due to a number of factors, including stress, anxiety or depression. In order to address your sleep problem, it is best to consult an experienced psychologist who can help you change your behaviour, manage feelings and emotions that may interfere with your sleep.",
  },
  {
    image: "/blog4.jpg",
    header: "Help your child find new friends",
    tag: "CHILDREN THERAPY",
    motherTag: "Friendship",
    date: "February 23, 2015",
    author: "Jaka Smid",
    body: "Anxiety is something that exists in everyone's life to a certain extent, and in a way it is medically known to be helpful as well. Because, anxiety helps us stay alert and be reactive to our circumstances, whether joyful or painful. However, when the anxiety reaches the stage where it overwhelms you mentally and physically, and affects your normal routine of life, you need the help of a clinical psychologist.",
  },
];
